<a href="https://colab.research.google.com/github/LakshayGangwal/Assignments-Data-Structures-in-Python/blob/main/Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
str="ajay barun chetna dinesh"

In [ ]:
names=str.split(" ")
print(names)

['ajay', 'barun', 'chetna', 'dinesh']


In [ ]:
np.fromstring('22 23 24 25',sep=" ")

array([22., 23., 24., 25.])

In [ ]:
np.arange(0,10,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
       7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [ ]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
 import random

In [ ]:
arr=np.random.randint(1,10,(4,7))
arr

array([[6, 2, 3, 6, 8, 7, 1],
       [5, 4, 8, 3, 9, 7, 5],
       [7, 3, 6, 9, 3, 1, 4],
       [8, 7, 7, 1, 7, 1, 9]])

In [ ]:
arr.reshape(2,2,7)

array([[[6, 2, 3, 6, 8, 7, 1],
        [5, 4, 8, 3, 9, 7, 5]],

       [[7, 3, 6, 9, 3, 1, 4],
        [8, 7, 7, 1, 7, 1, 9]]])

In [ ]:
ar=np.random.randint(1,10,(5,6))
ar

array([[4, 7, 4, 2, 3, 9],
       [4, 5, 4, 4, 7, 8],
       [5, 8, 3, 5, 8, 2],
       [2, 4, 1, 4, 1, 7],
       [4, 4, 9, 8, 6, 3]])

In [ ]:
ar.flatten()

array([4, 7, 4, 2, 3, 9, 4, 5, 4, 4, 7, 8, 5, 8, 3, 5, 8, 2, 2, 4, 1, 4,
       1, 7, 4, 4, 9, 8, 6, 3])

In [ ]:
f=np.array([120,7,5,6,8,200])
f

array([120,   7,   5,   6,   8, 200])

In [ ]:
np.sort(f)

array([  5,   6,   7,   8, 120, 200])

In [ ]:
np.searchsorted(f, 150)

np.int64(5)