<a href="https://colab.research.google.com/github/LakshayGangwal/Assignments-Data-Structures-in-Python/blob/main/Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
str="ajay barun chetna dinesh"

In [4]:
names=str.split(" ")
print(names)

['ajay', 'barun', 'chetna', 'dinesh']


In [5]:
np.fromstring('22 23 24 25',sep=" ")

array([22., 23., 24., 25.])

In [6]:
np.arange(0,10,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
       7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [7]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
 import random

In [10]:
arr=np.random.randint(1,10,(4,7))
arr

array([[4, 7, 1, 6, 9, 5, 5],
       [4, 4, 3, 4, 6, 5, 1],
       [6, 6, 1, 9, 6, 1, 7],
       [5, 3, 5, 2, 2, 4, 1]])

In [11]:
arr.reshape(2,2,7)

array([[[4, 7, 1, 6, 9, 5, 5],
        [4, 4, 3, 4, 6, 5, 1]],

       [[6, 6, 1, 9, 6, 1, 7],
        [5, 3, 5, 2, 2, 4, 1]]])

In [12]:
ar=np.random.randint(1,10,(5,6))
ar

array([[1, 1, 8, 6, 6, 5],
       [2, 8, 4, 8, 5, 1],
       [8, 2, 7, 7, 1, 6],
       [2, 8, 7, 4, 6, 3],
       [2, 8, 5, 9, 3, 9]])

In [13]:
ar.flatten()

array([1, 1, 8, 6, 6, 5, 2, 8, 4, 8, 5, 1, 8, 2, 7, 7, 1, 6, 2, 8, 7, 4,
       6, 3, 2, 8, 5, 9, 3, 9])

In [14]:
f=np.array([120,7,5,6,8,200])
f

array([120,   7,   5,   6,   8, 200])

In [15]:
np.sort(f)

array([  5,   6,   7,   8, 120, 200])

In [16]:
np.searchsorted(f, 150)

np.int64(5)

In [17]:
arr.ndim

2

In [18]:
arr

array([[4, 7, 1, 6, 9, 5, 5],
       [4, 4, 3, 4, 6, 5, 1],
       [6, 6, 1, 9, 6, 1, 7],
       [5, 3, 5, 2, 2, 4, 1]])

In [19]:
ar1=np.array([3, 4, 6, 1, 8, 5, 2])
print(ar1[::2])

[3 6 8 2]


In [20]:
ar1.dtype

dtype('int64')

In [21]:
ar1.shape

(7,)

In [22]:
arr.shape

(4, 7)

In [23]:
arr

array([[4, 7, 1, 6, 9, 5, 5],
       [4, 4, 3, 4, 6, 5, 1],
       [6, 6, 1, 9, 6, 1, 7],
       [5, 3, 5, 2, 2, 4, 1]])

In [24]:
from re import search
search("ajay",str)

<re.Match object; span=(0, 4), match='ajay'>

In [25]:
help(cumsum)

NameError: name 'cumsum' is not defined

In [ ]:
ar1

In [27]:
ar2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
ar2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [28]:
print(ar2[1,0])

6


In [32]:
l=[]
for i in range(20):
    l.append(np.random.randint(100))
l



[37, 86, 91, 66, 71, 86, 40, 19, 21, 0, 88, 32, 44, 75, 85, 81, 17, 56, 95, 29]