<a href="https://colab.research.google.com/github/LakshayGangwal/Assignments-Data-Structures-in-Python/blob/main/Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:
import numpy as np

In [43]:
str="ajay barun chetna dinesh"

In [44]:
names=str.split(" ")
print(names)

['ajay', 'barun', 'chetna', 'dinesh']


In [45]:
np.fromstring('22 23 24 25',sep=" ")

array([22., 23., 24., 25.])

In [46]:
np.arange(0,10,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
       7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [47]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [48]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [49]:
 import random

In [50]:
arr=np.random.randint(1,10,(4,7))
arr

array([[7, 7, 2, 7, 7, 7, 8],
       [3, 9, 5, 1, 6, 7, 1],
       [4, 1, 3, 7, 5, 1, 6],
       [7, 5, 2, 7, 3, 9, 8]])

In [51]:
arr.reshape(2,2,7)

array([[[7, 7, 2, 7, 7, 7, 8],
        [3, 9, 5, 1, 6, 7, 1]],

       [[4, 1, 3, 7, 5, 1, 6],
        [7, 5, 2, 7, 3, 9, 8]]])

In [52]:
ar=np.random.randint(1,10,(5,6))
ar

array([[4, 7, 8, 2, 3, 6],
       [1, 5, 9, 3, 8, 8],
       [9, 1, 2, 6, 1, 7],
       [3, 2, 4, 8, 1, 3],
       [2, 2, 3, 4, 2, 3]])

In [53]:
ar.flatten()

array([4, 7, 8, 2, 3, 6, 1, 5, 9, 3, 8, 8, 9, 1, 2, 6, 1, 7, 3, 2, 4, 8,
       1, 3, 2, 2, 3, 4, 2, 3])

In [54]:
f=np.array([120,7,5,6,8,200])
f

array([120,   7,   5,   6,   8, 200])

In [55]:
np.sort(f)

array([  5,   6,   7,   8, 120, 200])

In [56]:
np.searchsorted(f, 150)

np.int64(5)

In [57]:
arr.ndim

2

In [58]:
arr

array([[7, 7, 2, 7, 7, 7, 8],
       [3, 9, 5, 1, 6, 7, 1],
       [4, 1, 3, 7, 5, 1, 6],
       [7, 5, 2, 7, 3, 9, 8]])

In [59]:
ar1=np.array([3, 4, 6, 1, 8, 5, 2])
print(ar1[::2])

[3 6 8 2]


In [60]:
ar1.dtype

dtype('int64')

In [61]:
ar1.shape

(7,)

In [62]:
arr.shape

(4, 7)

In [63]:
arr

array([[7, 7, 2, 7, 7, 7, 8],
       [3, 9, 5, 1, 6, 7, 1],
       [4, 1, 3, 7, 5, 1, 6],
       [7, 5, 2, 7, 3, 9, 8]])

In [64]:
from re import search
search("ajay",str)

<re.Match object; span=(0, 4), match='ajay'>

In [65]:
help(cumsum)

NameError: name 'cumsum' is not defined

In [ ]:
ar1

In [ ]:
ar2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
ar2

In [ ]:
print(ar2[1,0])

In [ ]:
l=[]
for i in range(20):
    l.append(np.random.randint(100))
l



In [ ]:
import pandas as pd

In [ ]:
s=pd.Series([100,200,300])
s

In [66]:
s=pd.Series([100,200,300], index=['Ajay','Bijay','CJ'])
s

Ajay     100
Bijay    200
CJ       300
dtype: int64

In [68]:
df= pd.read_csv('services.csv')
df

FileNotFoundError: [Errno 2] No such file or directory: 'services.csv'

In [69]:
import os
print(os.getcwd())

/content
